### ISSUE TITLE
bad practice to include other extensions code in your extension

### ISSUE THREAD

**Issue by speedupmate** [adyenpayments/magento#116]
Hi Adyen Payment Method provider 

please don't include other extension providers code in your extension bundle cause this is really bad practice. I'm not speaking about intellectual property infringements (which is also a case here)  but the fact that you can provide outdated files that other extension providers might have to support and you can rewrite a large part of functionality that other extensions can depend on.

for example this is clearly a edited file from another extension. 
* https://github.com/adyenpayments/magento/blob/develop-2.1.2/skin/frontend/rwd/adyen/onestepcheckout/js/onestepcheckout.js 

You can always use prototype.js builtin functionality for overriding single functions or methods by wrapping ( see from API http://prototypejs.org/doc/latest/language/Function/prototype/wrap/ ) them and substituting with your own method when appropriate. 

If you really need to edit other extension files then please provide such rewrites as a patch or extra extension that can be enabled/disabled and is clearly separated.

**Comment by adyenpayments** [comment]
Hi Speedupmate,

We have removed it from the plugin code.

Regards,
Adyen

**Comment by speedupmate** [comment]
thanks for this I really appreciate it that you took the time for this

**Comment by mrafulfill** [comment]
You have promised to provide the onstepcheckout code externally, where can we find it?

**Comment by rikterbeek** [comment]
Hi mrafulfill,

For now it is downloadable here: https://github.com/Adyen/magento/releases/tag/2.2.2
see below OneStepCheckout.modifications.zip

In the development branch version this is not needed at all. This will be official released end of this week.

Regards,
Rik
Adyen
