### ISSUE TITLE
SEPA in backend only

### ISSUE THREAD

**Issue by seansan** [adyenpayments/magento#136]
Please create option for CC, bankstranfer and SEPA payment methods to set these options to BACKEND INLY

For processing orders with customers on the telephone

Solution can be found here:

http://magentotoolkit.com/code/magento-admin-only-payment-method/

1. add new admin option: enable backend only: yes/no
2. add two variables in code
3. load them from config

easy and quick fix: many many people happy

**Comment by adyenpayments** [comment]
Hi Sean,

This is implemented see #134 

Regards,
Adyen
