### ISSUE TITLE
Issues installing the adyen module.

### ISSUE THREAD

**Issue by paales** [adyenpayments/magento#170]
### Link to video is incorrect
In the `System > Config > Payment Methods > Adyen Default Settings` section there is a link to the instructional setup video, that links to `https://www.adyen.com/home/payment-services/plug-ins/magento#video` but that doesn't link to a video.

### I couldn't the Adyen backoffice.
Doesn't link to the actual backoffice. Google doesn't return the actual backoffice, the Adyen site doesn't communicate te word Adyen Backoffice.  When setting it up, it wasn't clear where the Adyen backoffice was. Was mentioned in the documentation, but would be handy if the documentation basics were implemented in the Admin Panel.

### System doesn't validate login settings in settings panel
There is not way to test if the current configuration is correct. It would be nice if it displayed a successmessage below the login fields for Adyen ws for example.

### Passwords fields are stored in plain text
The following fields are stored in plain text:
- `payment/adyen_abstract/notification_password`
- `payment/adyen_abstract/ws_password_test`
- `payment/adyen_abstract/ws_password_live`

**Comment by adyenpayments** [comment]
Hi Paales,

Thanks, we have removed the video from this page that is why you can't find it. I will change the url in the module. You can find the video here: vimeo.com/94005128

Regards,
Adyen

**Comment by paales** [comment]
@adyenpayments I'm currently installing the module, so I'll post my findings here.

**Comment by adyenpayments** [comment]
Hi Paales,

What do you mean with Doesn't link to the actual backoffice ?

Regards,
Adyen

**Comment by adyenpayments** [comment]
Hi Paales,

We have changed the video link and added the new manual we have now available with better explanation about how to setup the default settings of the module.

Regards,
Adyen

**Comment by adyenpayments** [comment]
Hi Paales,

Thanks for your comments. I have added links to the backoffice and password fields are now encrypted saved in the database and not shown in the configuration page. Validating the configuration is at the moment not possible. We have a project where we want to add APIs to get and set data to the Adyen Backoffice. This will solve this issue.

Regards,
Adyen
