### ISSUE TITLE
Magento broke after install extension

### ISSUE THREAD

**Issue by rickbenetti** [adyenpayments/magento#172]
I clean up my magento installation and when I add adyen files and folders I give this error:

```a:5:{i:0;s:221:"Error in file: "/vagrant/public/minori/app/code/community/Adyen/Payment/sql/adyen_setup/mysql4-upgrade-2.1.1-2.1.2.1.php" - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'minori.adyen_event_data' doesn't exist";i:1;s:950:"#0 /vagrant/public/minori/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')```

My magento not start because this.

I'm using a magento community 1.9.0.1

minori it's my database name.

**Comment by adyenpayments** [comment]
Hi rickbenetti,

It looks like you cleanup some adyen tables from your database. What you can do is manually add the adyen_event_data table. SQL code can you find in https://github.com/adyenpayments/magento/blob/develop-2.1.2/app/code/community/Adyen/Payment/sql/adyen_setup/mysql4-upgrade-0.1.0.3-0.1.0.4.php

Regards,
Adyen

**Comment by rickbenetti** [comment]
Correcting the table exists, but my database I use prefix, then the tables are only the prefix is ibc_

**Comment by adyenpayments** [comment]
Hi Rick,

I see the issue could you check if this fix will solve your problem ? Now using getTable function so prefixes will work as well.

Regards,

**Comment by rickbenetti** [comment]
Thanks works.

**Comment by rickbenetti** [comment]
Thank you,
really worked these changes.
