### ISSUE TITLE
RedirectShopper as Adyen status -> is this correct?

### ISSUE THREAD

**Issue by seansan** [adyenpayments/magento#177]
RedirectShopper as Adyen status -> is this correct?

I noticed because all Adyen status are in UPPER CAPS

And RedirectShopper does not really sound as an Adyen Status (more an event)

![image](https://cloud.githubusercontent.com/assets/652395/5816684/418342e2-a0a3-11e4-8e19-50d3bd02f47e.png)

**Comment by adyenpayments** [comment]
Hi Sean,

This is the status when 3D secure is used and the shopper is redirected to the 3D secure page.
If this stays in this status then the customer did not fill in his 3D secure code and has left the page.

Regards,
Adyen
