### ISSUE TITLE
Pending payment orders missing email and firstname/surname

### ISSUE THREAD

**Issue by seansan** [adyenpayments/magento#178]
We are seeing some strange behavior. And this did not occur before we used Adyen extension.

- A pending payment order exists 
- The client wants to transfer the payment manually 
- So we choose INVOICE and CAPTURE offline 
- Next thing I see is that the email and firstname/surname fields are suddenly empty

- This way the client does not receive order emails (there is no address)

Familiar?

Thx

![image](https://cloud.githubusercontent.com/assets/652395/5839344/e635adee-a18d-11e4-8d38-1bed15d18931.png)
![image](https://cloud.githubusercontent.com/assets/652395/5839398/3cc65366-a18e-11e4-98da-317c1607c420.png)

**Comment by adyenpayments** [comment]
Hi Sean,

I can't reproduce this problem. This is not controlled in our plugin. If you do a capture online we shoot in a call to Adyen if you choose offline the Adyen module is not used.

Regards,
Adyen

**Comment by seansan** [comment]
OK

I have no live example anymore but will monitor for future reference thanks
