### ISSUE TITLE
Urgent. Extension calling empty template file - ERR (3): Warning: include(): Filename cannot be empty in

### ISSUE THREAD

**Issue by seansan** [adyenpayments/magento#182]
HI, we See continuous logs of this error in logging. This is being caused by Adyen plugin. However we do not know if this is a config issue or coding issue. 

Most importantly empty template calls meay never occur. And should be neatly logged (and checked for being empty) before calling SetTemplate

**The original error:**

ERR (3): Warning: include(): Filename cannot be empty in /app/code/core/Mage/Core/Block/Template.php on line 241
ERR (3): Warning: include(): Failed opening '' for inclusion (include_path= many directories here)

**after debugging we found out this is the file/class causing it**

2015-01-28T12:02:57+00:00 DEBUG (7): File calling empty template file frontend/base/default/template/adyen/pdf/hpp.phtml on a Adyen_Payment_Block_Info_Hpp

**Debug Backtrace**

File	Line	Function
/app/code/core/Mage/Core/Block/Template.php	243	printDebugBacktrace
/app/code/core/Mage/Core/Block/Template.php	277	fetchView
/app/code/core/Mage/Core/Block/Template.php	291	renderView
/app/code/core/Mage/Core/Block/Abstract.php	919	_toHtml
/app/code/community/Adyen/Payment/Block/Info/Hpp.php	37	toHtml
/app/code/local/Mage/Sales/Model/Order/Pdf/Abstract.php	318	toPdf
/app/code/community/Fooman/EmailAttachments/Model/Order/Pdf/Order.php	59	insertOrder
/app/code/community/Fooman/EmailAttachments/Model/Observer.php	71	getPdf
/app/code/core/Mage/Core/Model/App.php	1338	beforeSendOrder
/app/code/core/Mage/Core/Model/App.php	1317	_callObserverMethod
/app/Mage.php	468	dispatchEvent
/app/code/community/Fooman/EmailAttachments/Model/Core/Email/Template/Mailer.php	71	dispatchEvent
/app/code/community/Fooman/EmailAttachments/Model/Core/Email/Template/Mailer.php	28	dispatchAttachEvent
/app/code/core/Mage/Sales/Model/Order.php	1340	send
/app/code/community/Adyen/Payment/Model/Process.php	645	sendNewOrderEmail
/app/code/community/Adyen/Payment/Model/Process.php	601	authorizePayment
/app/code/community/Adyen/Payment/Model/Process.php	95	_processNotifications
/app/code/community/Adyen/Payment/controllers/ProcessController.php	348	processResponse
/app/code/community/Adyen/Payment/controllers/ProcessController.php	274	processResponse
/app/code/core/Mage/Core/Controller/Varien/Action.php	418	insAction
/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php	250	dispatch
/app/code/core/Mage/Core/Controller/Varien/Front.php	172	match
/app/code/core/Mage/Core/Model/App.php	354	dispatch
/app/Mage.php	705	run
/index.php	89	run

**Comment by adyenpayments** [comment]
Hi Sean,

The toPdf() call should always listen to the adminhtml area templates. This one exists see: https://github.com/adyenpayments/magento/blob/master/app/design/adminhtml/default/default/template/adyen/pdf/hpp.phtml It is strange that in your environment it is calling the frontend area instead of adminhtml area. Do you know when this error is appearing ?

Regards,
Rik

**Comment by seansan** [comment]
NO we dont know

This error has boggled us for some time - no idea

thanks, Sean

**Comment by adyenpayments** [comment]
Hi Sean,

I have looked in Magento and we are using the default implementation of the toPdf() function. I see in your log that the Fooman/EmailAttachments/ module is doing something with the beforeSendOrder event. Think you should contact them.

Regards,
Adyen

**Comment by seansan** [comment]
​This extension is indeed called to allow for PDF attachments in email

Somehow this error is generated by Adyen ... or what makes you think this
is Fooman? (this helps me to direct the issue there)



​

**Comment by adyenpayments** [comment]
Hi Sean,

It is using the frontend area but should use the adminhtml area because here are all the templates for PDF's defined.

Regards,

**Comment by seansan** [comment]
AS I understand from Kristof (respected Magento developer) this works with any, if not all other PSP providers .... His short solution was to add a symlink in the Adyen extension from

adminthml/default/default/template/adyen/pdf/hpp.phtml
to
frontend/base/default/template/adyen/pdf/hpp.phtml

This way there will never be a problem .... and it works with any extension automating stuff

Hope it helps

**Comment by adyenpayments** [comment]
Hi Sean,

That is just not true.  Did some extra information and saw these topics:
http://stackoverflow.com/questions/8829214/pdf-invoice-generation-in-magento
http://www.magentocommerce.com/boards/%7Bpath:viewforum%7D/viewthread/270256/#t397540

Basically Magento always look in the adminhtml for PDF rendering so other external modules should do this as well.

Regards,
Adyen

**Comment by seansan** [comment]
Doesn't that confirm the proposed solution? Creating a symlink ....

**Comment by adyenpayments** [comment]
Hi Sean,

Yes this fixed the solution for you. The best solution is that pdf modules looks at the adminhtml area for PDF templates to let it work out of the box.

Regards,
Adyen

**Comment by hostep** [comment]
In case someone encounters this problem again (like we did just now), you need to add this line to your custom code:
```php
Mage::getDesign()->setArea('adminhtml');
```

Just like @adyenpayments was saying constantly, but for some reason I kept missing the point, maybe a code sample is more obvious for people like me :)

**Comment by seansan** [comment]
thanks! Problem though is that the temmplate is in an external extension
...

**Comment by shirtsofholl** [comment]
@hostep Where did you add this line of code? is that in `EmailAttachments/Model/Order/Pdf/Order.php` on line 47?
```
			Mage::getDesign()->setArea('adminhtml');
```

I did not get this working yet

**Comment by hostep** [comment]
@shirtsofholl, it was in a custom module which expands the webservices of Magento with functionality to return pdf's, relevant parts:

```php
// first get the current design area
$currentDesignArea = Mage::getDesign()->getArea();

// we need to explicitly set the Area to 'adminhtml', otherwise generating pdf's is using the 'frontend' area and can't find certain template files (for example the payment info block templates)
Mage::getDesign()->setArea(Mage_Core_Model_App_Area::AREA_ADMINHTML); // <- this is the one

// *** generate pdf's over here ***

// reset old design area
Mage::getDesign()->setArea($currentDesignArea);

```
