### ISSUE TITLE
2.2 on Ipad when POS payment success / error and client is re-directed to shop. Safari opens (instead of Chrome)

### ISSUE THREAD

**Issue by seansan** [adyenpayments/magento#193]
We use Chrome as a brwoser on ipad

when POS payment success / error and client is re-directed to shop

Safari is opened (and page can of course not be found)

**Comment by adyenpayments** [comment]
Hi Sean,

You need to use Safari for an IOS device. This is because the result url will always go back to safari that is a restriction of apple.

Regards,
Adyen
